openapi: 3.0.0
info:
  version: 1.0-SNAPSHOT-oas3
  title: ?lesson 1?
servers:
  - url: /v1
paths:
  /accounts/{id}:
    get:
      description: Get Balance
      operationId: accounts/getBalance
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: empty response
          content:
            application/json:
              schema:
                type: object
  /accounts:
    post:
      description: Create Account
      operationId: accounts/createAccount
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        '201':
          description: response
          content:
            application/json:
              schema:
                type: object
    get:
      description: Query Accounts
      operationId: accounts/queryAccounts
      parameters:
        - in: query
          name: customerId
          schema:
            type: integer
          description: Customer Id
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                type: object


